version: "3"
services: 
    mysql_container:
        image: mysql:latest
        container_name: mysql-container
        volumes:
            - ./payloadDB.sql:/docker-entrypoint-initdb.d/dump.sql
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            interval: 5s
            timeout: 15s
            retries: 3
    adminer_container:
        image: adminer:latest
        environment:
            ADMINER_DEFAULT_SERVER: mysql_container
        ports:
            - 8080:8080
    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: 'rabbitmq'
        ports:
            - 15672:15672
        volumes:
            - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.config
            - ./definitions.json:/etc/rabbitmq/definitions.json
        healthcheck:
            test: [ "CMD", "nc", "-z", "localhost", "5672" ]
            interval: 5s
            timeout: 15s
            retries: 3
    webservice:
        image: webservice-container
        ports:
            - 8081:8081
        depends_on:
            mysql_container:
                condition: service_healthy
            rabbitmq:
                condition: service_healthy
            